config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.connect '', :controller => 'login', :action => 'login'

  map.connect '/signup', :controller => 'login', :action => 'signup'
  map.connect '/screenshots', :controller => 'login', :action => 'screenshots'
  map.connect '/policy', :controller => 'login', :action => 'policy'
  map.connect '/terms', :controller => 'login', :action => 'terms'
  map.connect '/about', :controller => 'login', :action => 'about'
  
  map.home '/forums/index', :controller => 'forums', :action => 'index'

#  map.resources :users, :member => { :admin => :post } do |user|
#    user.resources :moderators
#  end

  map.resources :forums do |forum|
    forum.resources :topics, :name_prefix => nil do |topic|
      topic.resources :posts, :name_prefix => nil
      topic.resource :topic_monitorship, :controller => :monitorships, :name_prefix => nil
    end
    forum.resource :monitorship, :controller => :monitorships, :name_prefix => nil
  end

  map.resources :posts, :name_prefix => 'all_', :collection => { :search => :get }

  %w(user forum).each do |attr|
    map.resources :posts, :name_prefix => "#{attr}_", :path_prefix => "/#{attr.pluralize}/:#{attr}_id"
  end

  map.formatted_monitored_posts 'users/:user_id/monitored.:format', :controller => 'posts', :action => 'monitored'
  map.monitored_posts           'users/:user_id/monitored', :controller => 'posts', :action => 'monitored'

  map.connect ':controller/service.wsdl', :action => 'wsdl'

  map.connect ':controller/:action/:id.:format'
  map.connect ':controller/:action/:id'


end

app/models/user.rb
# A user from a company

class User < ActiveRecord::Base

  require_dependency 'digest/md5'

  belongs_to    :company
  has_many      :projects, :through => :project_permissions, :conditions => ['projects.completed_at IS NULL'], :order => "projects.customer_id, projects.name"
  has_many      :completed_projects, :through => :project_permissions, :conditions => ['projects.completed_at IS NOT NULL'], :source => :project, :order => "projects.customer_id, projects.name"
  has_many      :all_projects, :through => :project_permissions, :order => "projects.customer_id, projects.name", :source => :project
  has_many      :project_permissions, :dependent => :destroy
  has_many      :pages, :dependent => :nullify
  has_many      :tasks, :through => :task_owners
  has_many      :task_owners, :dependent => :destroy
  has_many      :work_logs, :dependent => :destroy
  has_many      :shouts, :dependent => :nullify

  has_many      :notifications, :dependent => :destroy
  has_many      :notifies, :through => :notifications, :source => :task

  has_many      :forums, :through => :moderatorships, :order => 'forums.name'
  has_many      :moderatorships, :dependent => :destroy

  has_many      :posts, :dependent => :destroy
  has_many      :topics, :dependent => :destroy

  has_many      :monitorships,:dependent => :destroy
  has_many      :monitored_topics, :through => :monitorships, :source => 'topic', :conditions => ['monitorships.active = ? AND monitorship_type = ?', true, 'topic'], :order => 'topics.replied_at desc'
  has_many      :monitored_forums, :through => :monitorships, :source => 'forum', :conditions => ['monitorships.active = ? AND monitorship_type = ?', true, 'forum'], :order => 'forums.position'

  has_many      :moderatorships, :dependent => :destroy
  has_many      :forums, :through => :moderatorships, :order => 'forums.name'

  has_many      :shout_channel_subscriptions, :dependent => :destroy
  has_many      :shout_channels, :through => :shout_channel_subscriptions, :source => :shout_channel

  has_many      :widgets, :order => "widgets.column, widgets.position", :dependent => :destroy

  has_many      :chats, :conditions => ["active = 0 OR active = 1"], :dependent => :destroy
  has_many      :chat_requests, :foreign_key => 'target_id', :class_name => 'Chat', :dependent => :destroy
  
  validates_length_of           :name,  :maximum=>200, :allow_nil => true
  validates_presence_of         :name

  validates_length_of           :username,  :maximum=>200, :allow_nil => true
  validates_presence_of         :username
  validates_uniqueness_of       :username, :scope => "company_id"

  validates_length_of           :password,  :maximum=>200, :allow_nil => true
  validates_presence_of         :password

  validates_length_of           :email,  :maximum=>200, :allow_nil => true
  validates_presence_of         :email

  validates_presence_of         :company

  after_destroy { |r|
    begin
      File.delete(r.avatar_path)
      File.delete(r.avatar_large_path)
    rescue
    end


    
  }

  before_create                 :generate_uuid

  after_create			:generate_widgets
  
  attr_protected :uuid, :autologin

  def path
    File.join("#{RAILS_ROOT}", 'store', 'avatars', self.company_id.to_s)
  end

  def avatar_path
    File.join(self.path, "#{self.id}")
  end

  def avatar_large_path
    File.join(self.path, "#{self.id}_large")
  end

  def avatar?
    File.exist? self.avatar_path
  end

  def generate_uuid
    @attributes['uuid'] = Digest::MD5.hexdigest( rand(100000000).to_s + Time.now.to_s)
    @attributes['autologin'] = Digest::MD5.hexdigest( rand(100000000).to_s + Time.now.to_s)
  end

  def new_widget
    Widget.new(:user => self, :company_id => self.company_id, :collapsed => 0, :configured => true)
  end
  
  def generate_widgets

    old_lang = Localization.lang

    Localization.lang(self.locale || 'en_US')

    w = new_widget
    w.name =  _("Top Tasks")
    w.widget_type = 0
    w.number = 5
    w.mine = true
    w.order_by = "priority"
    w.column = 0
    w.position = 0
    w.save
    
    w = new_widget
    w.name = _("Newest Tasks")
    w.widget_type = 0
    w.number = 5
    w.mine = false
    w.order_by = "date"
    w.column = 0
    w.position = 1
    w.save
    
    w = new_widget
    w.name = _("Recent Activities")
    w.widget_type = 2
    w.number = 20
    w.column = 2
    w.position = 0
    w.save
    
    w = new_widget
    w.name = _("Open Tasks")
    w.widget_type = 3
    w.number = 7
    w.mine = true
    w.column = 1
    w.position = 0
    w.save
    
    w = new_widget
    w.name = _("Projects")
    w.widget_type = 1
    w.number = 0
    w.column = 1
    w.position = 1
    w.save
    
    Localization.lang(old_lang)

  end
  
  def avatar_url(size=32, secure = false)
    if avatar?
      if size > 25 && File.exist?(avatar_large_path)
        "/users/avatar/#{self.id}?large=1&" + File.mtime(avatar_large_path).to_i.to_s
      else
        "/users/avatar/#{self.id}?" + File.mtime(avatar_path).to_i.to_s
      end
    else
      if secure
	"https://secure.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5.hexdigest(self.email.downcase)}&rating=PG&size=#{size}"
      else
	"http://www.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5.hexdigest(self.email.downcase)}&rating=PG&size=#{size}"
      end
    end
  end

  def display_name
    self.name
  end

  def login(subdomain = nil)
    unless (subdomain.nil? || ['www'].include?(subdomain))
      company = Company.find(:first, :conditions => ["subdomain = ?", subdomain.downcase])
      User.find( :first, :conditions => [ 'username = ? AND password = ? AND company_id = ?', self.username, self.password, company.id ] )
    else
      nil
    end
  end

  def can?(project, perm)
    @perm_cache ||= {}
    unless @perm_cache[project.id]
      @perm_cache[project.id] ||= {}
      self.project_permissions.each do | p |
        @perm_cache[p.project_id] ||= {}
        ['comment', 'work', 'close', 'report', 'create', 'edit', 'reassign', 'prioritize', 'milestone', 'grant', 'all'].each do |p_perm|
          @perm_cache[p.project_id][p_perm] = p.can?(p_perm)
        end
      end 
    end 

    (@perm_cache[project.id][perm] || false)
  end

  def can_all?(projects, perm)
    projects.each do |p|
      return false unless self.can?(p, perm)
    end
    true
  end

  def can_any?(project, perm)
    projects.each do |p|
      return true if self.can?(p, perm)
    end
    false
  end
  
  def admin?
    self.admin > 0
  end

  def currently_online
    User.find(:all, :conditions => ["company_id = ? AND last_seen_at > ?", self.company, Time.now.utc-5.minutes])
  end

  def moderator_of?(forum)
    moderatorships.count(:all, :conditions => ['forum_id = ?', (forum.is_a?(Forum) ? forum.id : forum)]) == 1
  end

  def online?
    (!self.last_ping_at.nil? && self.last_ping_at > 3.minutes.ago.utc)
  end

  def offline?
    !self.online?
  end
  
  def idle?
    ( (!self.last_ping_at.nil?) && (self.last_ping_at > 3.minutes.ago.utc) && (self.last_seen_at.nil? || self.last_seen_at < 10.minutes.ago.utc))
  end
  
  def online_status_name
    if self.last_ping_at.nil? || self.last_ping_at < 3.minutes.ago.utc
      return "<span class=\"status-offline\">#{self.name} (offline)</span>"
    elsif self.last_seen_at.nil? || self.last_seen_at < 10.minutes.ago.utc
      return "<span class=\"status-idle\">#{self.name} (idle)</span>"
    end
    "<span class=\"status-online\">#{self.name}</span>"
  end

  def tz
    unless @tz
      @tz = Timezone.get(self.time_zone)
    end
    @tz
  end

  def shout_nick
    n = nil
    n = name.gsub(/[^\s\w]+/, '').split(" ") if name
    n = ["Anonymous"] if(n.nil? || n.empty?)

    "#{n[0].chars.capitalize} #{n[1..-1].collect{|e| e.chars[0..0].upcase + "."}.join(' ')}".strip
  end

  def online_status_icon
    if self.idle?
      "/images/presence-idle.png"
    elsif self.online?
      "/images/presence-online.png"
    else 
      "/images/presence-offline.png"
    end
  end
  

end

app/views/layouts/_tabmenu.html.erb
<ul id="primary">
<% if current_user.seen_welcome.to_i == 0 %>
    <% if controller.controller_name == "activities" && controller.action_name == 'welcome' %>
        <li class="active"><%= link_to "#{_('Tutorial')}", { :controller => 'activities', :action => 'welcome'}, :class => "active"%></li>
    <% else %>
        <li><%= link_to "<span>#{_('Tutorial')}", { :controller => 'activities', :action => 'welcome'} %></li>
    <% end %>
<% end %>

<% if controller.controller_name == "activities" && controller.action_name != 'welcome' %>
    <li class="active"><%= link_to "#{_('Overview') }", { :controller => 'activities', :action => 'list'}, :class => "active"%>
        <ul>
            <li><%= link_to_remote _('Add New Widget'), :url => { :controller => 'widgets', :action => 'add'} %></li>
        </ul>
<% else %>
    <li><%= link_to "#{_('Overview')}", { :controller => 'activities', :action => 'list'} %>
<% end %>
</li>

  <% if controller.controller_name == "tasks" && !['timeline', 'new'].include?(controller.action_name) %>
  <li class="active"><%= link_to "#{_('Browse')}", { :controller => 'views', :action => 'browse'}, :class => "active" %>
  <% else %>
  <li><%= link_to "#{_('Browse')}", :controller => 'views', :action => 'browse' %>
  <% end %>
<ul>
  <li><%= link_to "#{_('Open Tasks')}", :controller => 'views', :action => 'all_tasks'%></li>
      <li><%= link_to _('My Open Tasks'), :controller => 'views', :action => 'my_tasks'%></li>
      <li><%= link_to _('My In Progress Tasks'), :controller => 'views', :action => 'my_in_progress_tasks'%></li>
      <li><%= link_to _('Unassigned Tasks'), :controller => 'views', :action => 'unassigned_tasks'%></li>
      <% project_ids = current_project_ids %>
      <% client_ids = current_projects.collect(&:customer_id).uniq.join(',')
         client_ids = "0" if client_ids.nil? || client_ids.empty?

         views = View.find(:all, :conditions => ["company_id = ? AND (user_id = ? or shared = 1) AND (filter_customer_id = 0 OR filter_customer_id IS NULL OR filter_customer_id IN (#{client_ids})) AND (filter_project_id = 0 OR filter_project_id IS NULL OR filter_project_id IN (#{project_ids}))", current_user.company_id, current_user.id], :order => "shared, name")
      for view in views %>
      <li><%= link_to(view.name, { :controller => 'views', :action => 'select', :id => view }) %><%= link_to("[#{_('Edit')}]", {:controller => 'views', :action => 'edit', :id => view}) if view.user_id == current_user.id %><%= "[#{_('Shared')}]" if view.user_id != current_user.id %></li>
  <% end %>
  <li><%= link_to "[#{_('New View')}]",  :controller => 'views', :action => 'new' %></li>
</ul>
 </li>

  <% if current_user.option_tracktime.to_i == 1%>
    <% if controller.controller_name == "timeline" && controller.action_name == "list" %>
    <li class="active"><%= link_to "#{_('Timeline')}", { :controller => 'timeline', :action => 'list'}, :class => "active" %></li>
    <% else %>
    <li><%= link_to "#{_('Timeline')}", :controller => 'timeline', :action => 'list' %></li>
    <% end %>
  <% end %>

  <% if controller.controller_name == "schedule"  %>
  <li class="active"><%= link_to "#{_('Schedule')}", {:controller => 'schedule', :action => 'list'}, :class => "active" %>
  <% else %>
  <li><%= link_to "#{_('Schedule')}", :controller => 'schedule', :action => 'list' %>
  <% end %>
    <ul>
  <li><%= link_to "#{_('Plan / GANTT')}", :controller => 'schedule', :action => 'gantt'%></li>
    </ul>
  </li>


  <% if current_user.option_tracktime.to_i == 1 && current_user.can_any?(current_user.projects, 'report') %>
    <% if controller.controller_name == "reports"  %>
    <li class="active"><%= link_to "#{_('Reports')}", {:controller => 'reports', :action => 'list'}, :class => "active" %></li>
    <% else %>
    <li><%= link_to "#{_('Reports')}", :controller => 'reports', :action => 'list' %></li>
    <% end %>
  <% end %>

<% if current_user.company.show_wiki? %>
<% if controller.controller_name == "wiki"  %>
      <li class="active"><%= link_to "#{_('Wiki')}", {:controller => 'wiki', :action => 'show', :id => nil}, :class => "active" %></li>
    <% else %>
      <li><%= link_to "#{_('Wiki')}", :controller => 'wiki', :action => 'show' %></li>
    <% end %>
<% end %>

<% if current_user.company.show_chat? %>
    <% if controller.controller_name == "shout"  %>
      <li class="active"><%= link_to "#{_('Chat')}", {:controller => 'shout', :action => 'list'}, :class => "active" %></li>
    <% else %>
      <li><%= link_to "#{_('Chat')}", :controller => 'shout', :action => 'list' %></li>
    <% end %>
 <% end %>

<% if current_user.company.show_forum? %>
    <% if ['forums', 'posts', 'topics'].include? controller.controller_name  %>
      <li class="active"><%= link_to "#{_('Forums')}", {:controller => 'forums', :action => 'index'}, :class => "active" %></li>
    <% else %>
      <li><%= link_to "#{_('Forums')}", :controller => 'forums', :action => 'index' %></li>
    <% end %>
  <% end %>

  <% if controller.controller_name == "project_files"  %>
  <li class="active"><%= link_to "#{_('Files')}", {:controller => 'project_files', :action => 'list'}, :class => "active" %> </li>
  <% else %>
  <li><%= link_to "#{_('Files')}", :controller => 'project_files', :action => 'list' %> </li>
  <% end %>

  <% if controller.controller_name == "projects" %>
  <li class="active"><%= link_to "#{_('Projects')}", {:controller => 'projects', :action => 'list'}, :class => "active" %>
  <% else %>
  <li><%= link_to "#{_('Projects')}", {:controller => 'projects', :action => 'list'} %>
  <% end %>
<% if current_user.create_projects? %>
<ul>
 <li><%= link_to _("New Project"), :controller => 'projects', :action => 'new' %></li>
</ul>
    <% end %>
 </li>

  <% if controller.controller_name == "tasks" && controller.action_name == 'new'  %>
  <li class="active"><%= link_to "#{_('New Task') + image_tag('tick.png',  :border => 0, :height => 16, :style => "margin-top:-2px;")}", {:controller => 'tasks', :action => 'new'}, :class => "active" %>
  <% else %>
  <li><%= link_to "#{_('New Task') + image_tag('tick.png',  :border => 0, :height => 16, :style => "margin-top:-2px;")}", {:controller => 'tasks', :action => 'new'} %>
  <% end %>
 </li>


 <li class="right"><a href="http://wiki.clockingit.com/help:<%=controller.controller_name%>:<%=controller.action_name%>" target="_blank"><img height="16" style="margin-top:-2px;" src="/images/help.png" border="0" /></a></li>

  <li class="right"><%= link_to "#{_('Log Out')}", { :controller => 'login', :action => 'logout'}, :class => "right" %></li>

  <% if controller.controller_name == "users" && controller.action_name == "edit_preferences" %>
  <li class="right active"><%= link_to "#{_('Preferences')}", { :controller => 'users', :action => 'edit_preferences'}, :class => "right active"%>
  <% else %>
  <li class="right"><%= link_to "#{_('Preferences')}", { :controller => 'users', :action => 'edit_preferences'}, :class => "right" %>
  <% end %>
  <% if current_user.admin > 0 %>
 <ul>
       <li><%= link_to _('Company Settings'), :controller => 'companies', :action => 'edit', :id => current_user.company_id %></li>
     </ul>
  <% end %>
  </li>

  <% if current_user.admin > 0 %>

  <% if current_user.option_externalclients.to_i == 1%>
  <% if controller.controller_name == "customers" %>
    <li class="right active"><%= link_to "#{_('Clients')}", { :controller => 'customers', :action => 'list'}, :class => "active"%></li>
    <% else %>
    <li class="right"><%= link_to "#{_('Clients')}", { :controller => 'customers', :action => 'list'}, :class => "right" %></li>
  <% end %>
  <% end %>


  <% if controller.controller_name == "users" && controller.action_name != "edit_preferences" %>
     <li class="active right"><%= link_to "#{_('Users')}", { :controller => 'users', :action => 'list'}, :class => "right active"%></li>
  <% else %>
     <li class="right"><%= link_to "#{_('Users')}", { :controller => 'users', :action => 'list'}, :class => "right" %></li>
  <% end %>

  <% end %>

  <li class="right" id="search_menu"><% form_tag( {:controller => 'search', :action => 'search'}, {:method => 'get'}) do %>
      <%= text_field_tag 'query', _('Search'), {:size => 10, :style => "font-size:9px;", :class => 'optional', :onfocus => "if($('query').value == '#{_('Search')}') {$('query').value = ''; $('query').removeClassName('optional');};"  }%>
    <% end %>
 </li>

  </ul>

app/views/layouts/popup.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
  <head>
    <%= javascript_include_merged :base %>
    <%= javascript_include_merged :tt %>
    <%= stylesheet_link_merged :tt %>
    <%= stylesheet_link_tag "print", { :media => "print" } %>
    <%= stylesheet_link_tag "shortlist" %>
    <%= auto_discovery_link_tag(:rss, {:controller => 'feeds', :action => 'rss', :id => current_user.uuid }) %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<% if !@internal.nil? && !@internal.css.nil? && @internal.css.length > 0 %>
<style type="text/css">
<%= @internal.css %>
</style>
<% end %>
</head>

  <body id="body" style="height:100%;">
    <div id="loading" style="z-index: 1000; position:absolute; right: 10px; top: 10px; width:70px; height:20px; color: white; padding:6px; display: none; "><img src="/images/spinner.gif" border="0"></div>
    <div id="tip" style="position:absolute;top:250px;left:250px;visibility:hidden;color:#666666;z-index:60;overflow:hidden;"><table border="0"><tr><td style="background-color:#ffffff;color:#666666;border:1px solid #CCCCCC;padding:0.2em;" id="message"><br/></td></tr></table></div>
    <table width="100%" cellspacing="0" cellpadding="0">
      <tr>
        <td valign="top" width="100%">
          <%= @content_for_layout %>
        </td>
      </tr>
    </table>

<script type="text/javascript" language="javascript" charset="utf-8">
// <![CDATA[
var userId=<%=current_user.id%>;
Event.observe(window, "load", function(e) {
<% if current_user.option_tooltips.to_i == 1 %>
  makeTooltips(1);
<% else %>
  makeTooltips(0);
<% end %>
});
// ]]>
</script>

</body>
</html>